### ISSUE TITLE
Horde 1-40 feedback

### ISSUE THREAD

**Issue by danielsmith604** [Doctorbeefy/JoanasGuide1#5]
This was all tested on the Emerald Dream x1 server with an orc shaman. I gave feedback before with my warrior a few months ago and it seems like you made some changes so I gave the newer version a go.

intro:

I think it used to be in the guide but it's gone now (or I didn't find it). It was mentioned that you should rarely skip mobs. It mentioned to kill mobs on the way to each quest destination. The exp adds up and honestly unless you stray off the guide's path or do every dungeon, you will fall behind the guide. I think that should be put back in there. Or maybe it was never in there and I'm just crazy.

Horde leveling guide 1-30

16-20 (part 3)
17) Mise as well finish the rest of the quest chain of delivering meats from xr to org and back to xr. It's small exp at this point but fast to do and on the way.

16-20 (part 4)
25) Free From the Hold isn't always available and even if it is, I don't think the exp you get is worth the 15-20 minutes it takes for him to ever so slowly walk back to bb.

Horde leveling guide 30-40

34-36
4) if you don't have "Encrusted Tail Fins", you should only have 1 quest too many at this point. I would suggest writing to not get Trollbane until a later time back in grom'gol since you won't need that until you go to Arathi.

34-36 (part2)
23) I still think Encrusted Tail Fins should be taken out of the guide. Unless the hunter class can solo it at lvl 34, the only way you can do this quest is with other people helping and since only 1 person can loot the quest item off each corpse, there's only like 10 murlocs, and the respawn is really really really long, I don't think it's worth being in the guide. Just my thoughts.

35) You need to hand in 60 Wool Cloth before getting the option to hand in 60 Silk Cloth. The wool cloth quest at this point will give fuck all exp. Should be done at a sooner point in the guide if possible.

37-37
6) Crown of Will must be picked up from UC first which is not done in the guide.

38-39
Should accept the last part of The Black Shield. All you gotta do is turn it in in TB and the guide eventually takes you there. Easy exp. You go to TB at 38-39 (part2) step 38. The quest npc is in the Hunter Rise, so really close to where you hand in Deadmire.

38-39 (part 2), 
33) For Jarl Needs a Blade, there is no razorspine. You need a BS to make Moonsteel Broadsword. I'd just take this quest out of the guide.

Q:Razzeric's Tweaking) Looks like you took getting the Seaforium Booster out of the guide. It's 19 or 20 on the map. Can do it easily before or after killing Deadmire (24)

36) Brackenwall has no hearth. Last hearth was set at xroads.

**Comment by Doctorbeefy** [comment]
Sorry due to my inactivity I just saw this I will fix and update : ]

**Comment by Doctorbeefy** [comment]
Actually I'll update now. Apparently I never push out the newest update I have most of that already fixed

**Comment by Doctorbeefy** [comment]
Razzeric's Tweaking is later in the guide 43-44
